### PR TITLE
[OR-1790] fix path

### PR DESCRIPTION
**Pull request by steven94kr**
- fix path

I'm sorry for my missing.
Thank you!

### CODE REVIEW

**Review by theo-learner — COMMENTED** [review]
Thank you. Could you check the path in tokamak-public-release.yml#L80?

**Comment by rlgns98kr** [comment]
> Thank you. Could you check the path in tokamak-public-release.yml#L80?

Do you mean this line ?
```
echo "VERSION=$(jq -r .version ./packages/tokamak/${{ matrix.package }}/package.json)" >> $GITHUB_OUTPUT
```

**Comment by boohyung** [comment]
> > Thank you. Could you check the path in tokamak-public-release.yml#L80?
> 
> Do you mean this line ?
> 
> ```
> echo "VERSION=$(jq -r .version ./packages/tokamak/${{ matrix.package }}/package.json)" >> $GITHUB_OUTPUT
> ```

Yes. I think `./packages/${{ matrix.package }}/package.json` is right path.

**Comment by rlgns98kr** [comment]
@boohyung 
Should we deploy optimism's instead of ours?

**Comment by boohyung** [comment]
> @boohyung Should we deploy optimism's instead of ours?

Sorry I missed it. Let approve this PR. Thanks a lot, Steven!

**Review by theo-learner — APPROVED** [review]
+1

**Pull request merged**
