### PR TITLE
feat(OR-1241): tracks SCC, CTC block number

### PR DESCRIPTION
**Pull request by ghost**
## Description
Related to [OR-1241](https://onther.atlassian.net/browse/OR-1241), we need to create the alarms to notify when mismatching between SCC, CTC block number vs L2 block number.

### How can we test this feature?
To test this feature, we need to update `batch-submitter` instance on our devnet env(Goerli), query and compare the value of two metrics `batch_submitter_sequencer_block_number` and `batch_submitter_proposer_block_number` with the L2 block number.

[OR-1241]: https://onther.atlassian.net/browse/OR-1241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by boohyung** [comment]
Please set the reviewers and assignees.

**Comment by 0x6e616d** [comment]
> Please set the reviewers and assignees.

Updated, tks you

**Comment by boohyung** [comment]
How do we test this feature in our environment? Could you describe the short guide in PR?

**Comment by 0x6e616d** [comment]
> How do we test this feature in our environment? Could you describe the short guide in PR?

Updated for the short description

**Review by steven94kr — APPROVED** [review]
Thank you very much! 👏🏻😍

**Review by theo-learner — APPROVED** [review]
+1

**Pull request merged**
